[package]
name = "imgcat"
version = "0.1.2"
description = "concatenate and print images in iterm2"
keywords = ["image", "terminal"]
readme = "README.md"
authors = ["ltoddy <tao.liu1@thoughtworks.com>"]
edition = "2024"
license = "MIT"
homepage = "https://github.com/small-parts/imgcat-rs"
repository = "https://github.com/small-parts/imgcat-rs"
categories = ["development-tools"]
include = [
    "src/**/*.rs",
    "Cargo.toml",
    "LICENSE",
    "README.md",
    "me.jpg",
    "rustfmt.toml"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.22"
clap = { version = "4.6", features = ["derive"] }

[profile.dev]
debug = 0

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
